"""Validate the canonical JSON and generate the offline browser data bundle."""
import json
from pathlib import Path
from urllib.parse import urlparse
root=Path(__file__).resolve().parent
courts=json.loads((root/'courts.json').read_text())
assert len({c['id'] for c in courts})==len(courts), 'Duplicate venue IDs'
for c in courts:
    assert c['name'] and c['map']['kind'] in ('shared_link','search','coordinates')
    for u in [c['map']['url']]+[x['url'] for x in c['booking']['links']]:
        assert urlparse(u).scheme=='https' and urlparse(u).netloc, f'Unsafe URL: {u}'
    for p in c['prices']:
        assert p['amount']>0 and p['currency']=='SAR'
        assert p['durationMinutes'] is None or p['durationMinutes']>0
    for p in c['booking']['contacts']:
        assert (p['e164'] is not None)==(p['formatStatus']=='plausible')
(root/'courts-data.js').write_text('// Generated by build-data.py. Edit courts.json instead.\nwindow.COURTS_DATA = '+json.dumps(courts,ensure_ascii=False,indent=2)+';\n')
print(f'Validated and built {len(courts)} venues.')
