// Generated by build-data.py. Edit courts.json instead.
window.COURTS_DATA = [
  {
    "id": "al-qirawan",
    "name": "القيروان",
    "locationText": "القيروان",
    "map": {
      "url": "https://maps.app.goo.gl/WugYoKxFfm8boLSs8",
      "kind": "shared_link",
      "entranceVerified": false
    },
    "booking": {
      "method": "واتساب",
      "contacts": [
        {
          "type": "whatsapp",
          "raw": "966557725444",
          "e164": "+966557725444",
          "formatStatus": "plausible",
          "ownershipVerified": false
        }
      ],
      "links": []
    },
    "prices": [
      {
        "amount": 110,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": null,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 155,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 90,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 210,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 120,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "تتوفر خيارات حجز لمدة ساعة ونصف أو ساعتين.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "duration_unspecified"
    ]
  },
  {
    "id": "al-arid",
    "name": "العارض",
    "locationText": "العارض",
    "map": {
      "url": "https://maps.app.goo.gl/HvfSkBHHYgiw7RCeA",
      "kind": "shared_link",
      "entranceVerified": false
    },
    "booking": {
      "method": "واتساب",
      "contacts": [
        {
          "type": "whatsapp",
          "raw": "966557725444",
          "e164": "+966557725444",
          "formatStatus": "plausible",
          "ownershipVerified": false
        }
      ],
      "links": []
    },
    "prices": [
      {
        "amount": 110,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": null,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 155,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 90,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 210,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 120,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "تتوفر خيارات حجز لمدة ساعة ونصف أو ساعتين.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "duration_unspecified"
    ]
  },
  {
    "id": "shawaya",
    "name": "شوايات",
    "locationText": null,
    "map": {
      "url": "https://maps.app.goo.gl/nhSn1ZzEQ479vEQ59",
      "kind": "shared_link",
      "entranceVerified": false
    },
    "booking": {
      "method": "تطبيق ملاعب",
      "contacts": [],
      "links": [
        {
          "type": "android",
          "url": "https://play.google.com/store/apps/details?id=com.malaebapp.app",
          "label": "Google Play"
        },
        {
          "type": "ios",
          "url": "https://itunes.apple.com/us/app/malaeb-app/id1094201670?ls=1&mt=8",
          "label": "App Store"
        }
      ]
    },
    "prices": [
      {
        "amount": 110,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 140,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 90,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 190,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 120,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "الحجز من خلال تطبيق ملاعب.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "location_unspecified"
    ]
  },
  {
    "id": "al-yamamah",
    "name": "جامعة اليمامة",
    "locationText": "القيروان · طريق الملك فهد",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Al%20Yamamah%20University%20Riyadh",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "واتساب",
      "contacts": [
        {
          "type": "whatsapp",
          "raw": "9665599888307",
          "e164": null,
          "formatStatus": "needs_review",
          "ownershipVerified": false
        }
      ],
      "links": []
    },
    "prices": [
      {
        "amount": 150,
        "currency": "SAR",
        "currencyStatus": "assumed",
        "durationMinutes": null,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 200,
        "currency": "SAR",
        "currencyStatus": "assumed",
        "durationMinutes": 90,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 250,
        "currency": "SAR",
        "currencyStatus": "assumed",
        "durationMinutes": 120,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "موقع الجامعة؛ يرجى تأكيد بوابة الملعب. العملة مفترضة بالريال في السجل الأصلي.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "phone_format",
      "duration_unspecified",
      "currency_assumed"
    ]
  },
  {
    "id": "prince-sultan",
    "name": "جامعة الأمير سلطان",
    "locationText": "شارع رفحاء",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Prince%20Sultan%20University%20Riyadh",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "إن تنس",
      "contacts": [],
      "links": [
        {
          "type": "booking",
          "url": "https://intennis-sa.com/book/hourly",
          "label": "إن تنس"
        }
      ]
    },
    "prices": [],
    "notes": "يرجى تأكيد مدخل الملعب مع جهة الحجز.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": []
  },
  {
    "id": "digital-city",
    "name": "المدينة الرقمية",
    "locationText": "كراون بلازا المدينة الرقمية",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Crowne%20Plaza%20Riyadh%20RDC%20Hotel",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "إن تنس",
      "contacts": [],
      "links": [
        {
          "type": "booking",
          "url": "https://intennis-sa.com/book/hourly",
          "label": "إن تنس"
        }
      ]
    },
    "prices": [
      {
        "amount": 180,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": null,
        "timeWindow": null
      },
      {
        "amount": 360,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 120,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "الموقع مذكور في تقرير ثمانية؛ يرجى تأكيد مدخل الملعب.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": []
  },
  {
    "id": "net-tennis",
    "name": "نت تنس",
    "locationText": "الدرعية",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Net%20Tennis%20Academy%20Diriyah",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "الموقع الإلكتروني",
      "contacts": [],
      "links": [
        {
          "type": "website",
          "url": "https://netacademy.sa",
          "label": "موقع المنشأة"
        }
      ]
    },
    "prices": [
      {
        "amount": 200,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "قرب بادل أب وملاعب المونديال، بحسب تقرير ثمانية.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": []
  },
  {
    "id": "racket",
    "name": "راكت",
    "locationText": "مركز الملك سلمان الاجتماعي",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Racket%20Tennis%20King%20Salman%20Social%20Center%20Riyadh",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "تطبيق سنجاب",
      "contacts": [],
      "links": []
    },
    "prices": [
      {
        "amount": 199,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "الحجز عبر تطبيق سنجاب؛ رابط التطبيق غير مسجّل.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": []
  },
  {
    "id": "tennis-home",
    "name": "بيت التنس",
    "locationText": null,
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Tennis%20Home%20Academy%20Riyadh",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "الموقع الإلكتروني",
      "contacts": [],
      "links": [
        {
          "type": "website",
          "url": "https://tennishomeacademy.com",
          "label": "موقع المنشأة"
        }
      ]
    },
    "prices": [
      {
        "amount": 286,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 120,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "السعر المسجّل لحجز ساعتين. وردت ٣ ملاعب في الملاحظات و٣ فروع في المصدر؛ الفرع المقصود يحتاج تحديدًا.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "location_unspecified"
    ]
  },
  {
    "id": "salwa",
    "name": "كمباوند سلوى",
    "locationText": null,
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Salwa%20Garden%20Village%20Riyadh",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "واتساب · يونس",
      "contacts": [
        {
          "type": "whatsapp",
          "raw": "34680800055",
          "e164": "+34680800055",
          "formatStatus": "plausible",
          "ownershipVerified": false
        }
      ],
      "links": []
    },
    "prices": [
      {
        "amount": 110,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": null,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "الموقع المرجّح هو Salwa Garden Village؛ يُؤكّد مع يونس. شروط دخول غير السكان غير مسجّلة.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "duration_unspecified",
      "location_unspecified"
    ]
  },
  {
    "id": "najd",
    "name": "كمباوند نجد",
    "locationText": "غرناطة",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=Najd%20Compound%20Ghirnatah%20Riyadh",
      "kind": "search",
      "entranceVerified": false
    },
    "booking": {
      "method": "واتساب · Iggy",
      "contacts": [
        {
          "type": "whatsapp",
          "raw": "966504112694",
          "e164": "+966504112694",
          "formatStatus": "plausible",
          "ownershipVerified": false
        }
      ],
      "links": [
        {
          "type": "website",
          "url": "https://najdcompound.com/",
          "label": "موقع المنشأة"
        }
      ]
    },
    "prices": [
      {
        "amount": 150,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": "الذروة",
        "timeWindow": "٦ مساءً – ١٠ مساءً"
      },
      {
        "amount": 99,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": "خارج الذروة",
        "timeWindow": "٥ – ٨ صباحًا، ٥ – ٦ مساءً، ١١ مساءً – ٥ صباحًا"
      }
    ],
    "notes": "٣ ملاعب مضاءة بحسب الموقع الرسمي. شروط دخول غير السكان تحتاج تأكيدًا. تسعيرة الفترة من ١٠ إلى ١١ مساءً غير مسجّلة.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": []
  },
  {
    "id": "spin",
    "name": "وادي حنيفة — Spin",
    "locationText": "وادي حنيفة",
    "map": {
      "url": "https://maps.app.goo.gl/E9nEb3JmCVLXu7SV7?g_st=ic",
      "kind": "shared_link",
      "entranceVerified": false
    },
    "booking": {
      "method": "Matchpoint",
      "contacts": [
        {
          "type": "whatsapp",
          "raw": "966557000674",
          "e164": "+966557000674",
          "formatStatus": "plausible",
          "ownershipVerified": false
        }
      ],
      "links": [
        {
          "type": "booking",
          "url": "https://matchpointksa.com/rent-court/p502506753",
          "label": "Matchpoint"
        }
      ]
    },
    "prices": [
      {
        "amount": 200,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": null,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "السعر ورابط الموقع من الملاحظات الأصلية.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "duration_unspecified"
    ]
  },
  {
    "id": "intercontinental",
    "name": "الإنتركونتيننتال",
    "locationText": null,
    "map": {
      "url": "https://maps.app.goo.gl/7LZbBFji8xC3KigTA?g_st=ic",
      "kind": "shared_link",
      "entranceVerified": false
    },
    "booking": {
      "method": "اتصال هاتفي",
      "contacts": [
        {
          "type": "telephone",
          "raw": "966114655000",
          "e164": "+966114655000",
          "formatStatus": "plausible",
          "ownershipVerified": false
        }
      ],
      "links": []
    },
    "prices": [
      {
        "amount": 230,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "الحجز في اليوم نفسه عبر الهاتف، ابتداءً من ١٠ صباحًا.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "location_unspecified"
    ]
  },
  {
    "id": "fal",
    "name": "فال كمباوند",
    "locationText": "طريق المطار · مقابل جامعة الإمام",
    "map": {
      "url": "https://www.google.com/maps/search/?api=1&query=24.812028,46.715833",
      "kind": "coordinates",
      "entranceVerified": false
    },
    "booking": {
      "method": "بانتظار تفاصيل الحجز",
      "contacts": [],
      "links": [
        {
          "type": "website",
          "url": "https://falcompounds.org/",
          "label": "موقع المنشأة"
        }
      ]
    },
    "prices": [],
    "notes": "ملعبان بحسب الموقع الرسمي. بحسب الملاحظات، أُرسل استفسار بالبريد وبانتظار الرد عن الأسعار والحجز وشروط الدخول.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": []
  },
  {
    "id": "king-saud",
    "name": "ملعب جامعة الملك سعود",
    "locationText": null,
    "map": {
      "url": "https://maps.app.goo.gl/k9PCpDxv6CMRGqjF7",
      "kind": "shared_link",
      "entranceVerified": false
    },
    "booking": {
      "method": "نموذج الحجز",
      "contacts": [],
      "links": [
        {
          "type": "booking",
          "url": "https://script.google.com/macros/s/AKfycbw54XLyouWpnqVkndKVVueGh9HrqigebxWqw0MvHxg51XRxV3qEDHUSu00xc55Ep7Ejlw/exec",
          "label": "نموذج الحجز"
        }
      ]
    },
    "prices": [
      {
        "amount": 150,
        "currency": "SAR",
        "currencyStatus": "recorded",
        "durationMinutes": 60,
        "label": null,
        "timeWindow": null
      }
    ],
    "notes": "الفترة المسائية: ٤ مساءً – ٥ صباحًا. تأكد من صحة البيانات ووصول بريد التأكيد؛ يُلغى الحجز تلقائيًا إذا كانت البيانات خاطئة. للإلغاء تواصل عبر واتساب قبل الموعد بيوم على الأقل؛ رقم الإلغاء غير مسجّل.",
    "provenance": {
      "source": "existing_directory",
      "verifiedAt": null
    },
    "issues": [
      "location_unspecified"
    ]
  }
];
